### ISSUE TITLE
Log in Not working 

### ISSUE THREAD

**Issue by AlishiaR** [wismna/ModernKeePass#1] opened 2018-05-31 12:58 UTC
I can't log into my ModernKeePass with my password. It's the exact same one I always use and now I get an Error: wrong password.

**Comment by wismna** [comment] 2018-06-04 12:58
Hi,

Thank you for trying ModernKeePass! All right, could you give me some information about your kdbx file: 

- Encryption algorithm used
- Key derivation algorithm used
- Are there any specific things in your DB? E.g. special fields, attachments or the like?

Regards

**Comment by ghost** [comment] 2019-11-13 17:59
A similar problem: #4

**Comment by wismna** [comment] 2020-04-23 17:30
Hi,

It's been a while since I had the opportunity to work on the project, so sorry for the long delay.
Regarding your issue, it's unfortunate. It's something I can't really reproduce on my side.
However, this issue happened to a few people using the app, so I decided to fix it once and for all.

Here's what I implemented:

- On saving, the database integrity is checked. If the app can't re-open it, it won't try to write the changes to the database file.
- The file write itself uses a transactional model, meaning that the changes will be committed to the original file if and only if there were no issues.

So, worst case scenario, your new changes will not be written to the database file, but at least the original file won't risk corruption.

As for why this corruption occured in the first place, I suspect this may be due to the way Windows Apps work, and a poor design decision on my part.
ModernKeePass used to auto-save the database on quit. However, Windows only gives the app a few seconds to do so. So in some cases, the app could actually be forcibly closed by Windows before being able to finish the write operation, resulting in corruption. With the above changes, this should not happen anymore, but I also improved the auto-save feature. It will try to save on quit only if these conditions are met:
- Database size is less than 1MB. Bigger size start to increase write time exponentially.
- There were actual changes in the database.

I will publish this new version very soon. Again, sorry about the inconvenience you experienced...

**Closed as completed by wismna** 2020-04-23 17:30 UTC
